#!/bin/bash

project_dir=`dirname $0`
cd $project_dir ;

stopfunc () {
    pkill -f duckling ;
    pkill -f rasa_env ;
    pkill -f ngrok ;
    echo "Killed all chefbot processes"
}

if [ $1 == serve ]
then
    stopfunc
    # Start Ngrok
    ngrok http 5005 > /dev/null &
    # Update website
    sleep 3	
	python3 update_website.py
    # Start Duckling
    ./duckling/duckling-example-exe -p 8000 &
    # Start Rasa
    cd bot ; rasa run actions --port 5056 & rasa run --enable-api --cors 'https://edward-rees.com' --debug
else
    if [ $1 == shell ]
    then
        stopfunc
        # Start Duckling
        ./duckling/duckling-example-exe -p 8000 &
        # Start Rasa
        cd bot ; rasa run actions --port 5056 & rasa shell --debug
    fi

fi

if [ $1 == kill ]
then
    stopfunc
fi

