# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# pipeline:
#   - name: "SpacyNLP"
#   - name: "SpacyTokenizer"
#   - name: "SpacyFeaturizer"
#   - name: "RegexFeaturizer"
#   - name: "CRFEntityExtractor"
#   - name: "EntitySynonymMapper"
#   - name: DucklingHTTPExtractor
#     url: http://localhost:8000
#     dimensions:
#       - duration
#     local: 'en_GB'
#     timezone: 'Europe/London'
#   - name: "SklearnIntentClassifier"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
      - duration
    local: 'en_GB'
    timezone: 'Europe/London'
  - name: EmbeddingIntentClassifier

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 4
  - name: KerasPolicy
  - name: FormPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
